### ISSUE TITLE
PackageСloud.io

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#130]
Research https://packagecloud.io/
* Compare with Bintray: pros/cons
* Provide report/overview (see examples: [Travis](https://github.com/StackStorm/st2-packages/issues/5), [CircleCI](https://github.com/StackStorm/st2-packages/issues/6), [Drone v0.4](https://github.com/StackStorm/st2-packages/issues/9), [Drone v0.3](https://github.com/StackStorm/st2-packages/issues/10))
* Integrate in parallel with Bintray (without removing Bintray for now).

#### TODO (updated):
* [x] Basic PackageCloud.io integration #140 
* [x] Enable in `st2-packages` repo
* [x] Enable in `st2web` repo (stable/unstable) https://github.com/StackStorm/st2web/pull/284 https://github.com/StackStorm/st2web/pull/285
* [x] Enable in `st2flow` repo https://github.com/StackStorm/st2flow/pull/79
* [x] Enable in `st2-enterprise-auth-backend-ldap` repo https://github.com/StackStorm/st2-enterprise-auth-backend-ldap/pull/10
* [x] Fix [`filename: has already been taken`](https://github.com/StackStorm/st2-packages/blob/d35721d9c6b70c0108a72bba4885ca4a476004ae/.circle/packagecloud.sh#L171-L176) error. Package with the same name/version/revision should be overwritten during upload. [`package_cloud`](https://rubygems.org/gems/package_cloud) ruby gem changes **OR** enable revision discovery/increment for `st2mistral` https://github.com/StackStorm/st2-packages/pull/174
* [x] Add [`MAX_REVISIONS`](https://github.com/StackStorm/st2-packages/blob/d35721d9c6b70c0108a72bba4885ca4a476004ae/.circle/packagecloud.sh#L12-L15) feature to keep storage under control and delete obsolete files https://github.com/StackStorm/st2-packages/pull/170
* [ ] Fix small [stability issues](https://github.com/StackStorm/st2-packages/blob/d35721d9c6b70c0108a72bba4885ca4a476004ae/.circle/packagecloud.sh#L200-L213)
* [x] Enable in `st2` repo, so we can deploy `stable` packages
* [x] Enable revision discovery based on PackageCloud repos, instead of Bintray https://github.com/StackStorm/st2-packages/pull/173
* [x] Merge Installation instructions docs [v1.3](https://github.com/StackStorm/st2docs/pull/62) and  [latest](https://github.com/StackStorm/st2docs/pull/63)
* [ ] Research/Try `yum`/`apt` [repo mirroring](https://packagecloud.io/StackStorm/staging-unstable/mirror)

**Comment by armab** [comment]
Some more info about PackageCloud starting from: https://stackstorm.slack.com/archives/standup/p1454335755000792

**Comment by enykeev** [comment]
I've published the first set of packages on my own packagecloud organization called "mechanica" and managed to provision https://github.com/enykeev/st2testground with it. The PR in question is #140.

A number of observations I've gather throughout the process:
- The only two functions of official cli client that works well enough for us is `push` and `master_token`. Client doesn't allow to list packages (to determine latest revision) or add read tokens (so we can give them to our users in a more granular way). I haven't been able to create private repo with it either, though it might be related to poorly documented parameters or my slightly curved hands.
- You can do all this stuff through direct API calls, but this means having `curl` and `jq` as dependencies (unless you're ok to parse json with awk which I'm not). Documentation doesn't mention python client, but we will likely to need it anyway to build st2 actions on top of it, so it might be our way out. But writing client would require additional effort.
- As per documentation, audit is only available for private repos so either we make our public repo 'private' too and just share master token with anyone (which will affect usability) or get along without having an audit for public packages which is not ideal either.
- The hierarchy of repo is different from bintray. Each repo contains packages for every platform, but lacks information on package stability. This way, instead of `{trusty|whezzy|jessie|el6|el7}{_staging}` (10 repos) we would need `stackstorm\{st2|st2enterprise}{_staging}{_unstable}` (8 repos, but more complex naming). I still don't feel particularly clear on why do we need both `staging` and `unstable`, but I guess I'll just trust you on that one.
- PackageCloud also enforces some naming conventions to how you refer to specific distro, so internally in our script we have to convert 'el7' to 'el/7' and 'trusty' to 'ubuntu/trusty'.
- Repo have no additional meta besides its name and privacy settings so no configs are needed.
- PackageCloud has two level approach to access tokens where master tokens are used to generate read tokens which is later used to authenticate against the repo. Revoking master token makes all read tokens issued by him invalid. How exactly are we going to integrate this mechanics into our workflow is a question for additional investigation.
- Most of the problems I had with packagecloud is related tot he fact I had to retain backward compatibility with bintray script to use them side by side. There's plenty of room for optimization when we settle on either one or the other.

At that point, I would like us to review and merge #140 so we can add it to the rest of our repos (web, flow, st2) and evaluate the stability. I have 12 more days of trial on this account so let's see if they manage to disappoint us in that time frame =)

To test new repos yourself, go to https://packagecloud.io/mechanica/st2_staging/install and try to install the packages from it instead of bintray.

**Comment by armab** [comment]
Thanks for the info :+1: 

> I still don't feel particularly clear on why do we need both staging and unstable, but I guess I'll just 
trust you on that one.

From what I know, overall idea is: 
- We build/deploy packages to `staging` repos and Hook from CircleCI to st2 staging box, saying "packages are ready". We can build both `stable` (`1.4dev`) and `unstable` (`1.3`) packages.
- st2 staging box installs just created/uploaded packages from staging repo and performs all unit/integration/end2end tests.
- If staging box decides that packages are good enough - it deploys the same packages, but in `production` repos. Since that - packages are available for users.


From that logic: 
* Staging repos are just for internal testing. Consider it as a sandbox. Production repos are ready to use by users. That's why `staging`/`production` is needed.
* It's really needed to give users repo with `stable` st2 version like `1.3`. If you'll have unstable `1.4dev` versions in the same repo - they will be installed by default, instead of stable `1.3`. That's why `stable`/`unstable` is needed.
* There is also need to have fully mirrored `staging`/`production` repos, so they'll work in 100% the same way. When working with staging or production repos - you just remove word in repo url and expect same behavior.

**Comment by armab** [comment]
Regarding repo naming, small proposal is to remove `st2` as a prefix, looks already nice with `stackstorm` organization in url: 

Instead of: https://packagecloud.io/stackstorm/st2_staging_unstable some examples: 

#### Production (for users):
* https://packagecloud.io/stackstorm/stable
* https://packagecloud.io/stackstorm/unstable

#### Staging (for internal use):
* https://packagecloud.io/stackstorm/staging-stable
* https://packagecloud.io/stackstorm/staging-unstable

We include all the stuff in these repos like `mistral`, even `python` in el6.

Enterprise user will see something like:
* https://packagecloud.io/stackstorm/enterprise-stable
* https://packagecloud.io/stackstorm/enterprise-unstable

---
Also `_` or `-` as a separator - meh for me. Just followed ubuntu usual way with `-` in these examples.

**Comment by armab** [comment]
I really liked that they suggest Mirroring:
![xqhk4jr 1](https://cloud.githubusercontent.com/assets/1533818/12796779/4358bd62-cac9-11e5-8649-db65129b8e4b.png)

Hadn't in mind such idea at all. So we can have everything under `stackstorm.net`, but use their API to upload packages.

**Comment by enykeev** [comment]
> Regarding repo naming, small proposal is to remove st2 as a prefix

I did that in case we decide to add another repo, not related to st2. Also, this is how others do, see https://packagecloud.io/raintank for example.

**Comment by armab** [comment]
In my mind it's overcomplication, it would be just better naming :)

I don't think we'll need another repo in nearest time, not related to `st2`. Because we put already everything in one single place and I think it's OK. Single repo can contain hundreds of different packages. Previously it was just `deb`: http://downloads.stackstorm.net/deb/

Also see these discussions: 
https://github.com/StackStorm/discussions/issues/123
https://github.com/StackStorm/discussions/issues/130
(main discussion was in Slack based on these Github topics, but anyway you got the point - most of the team was involved in decision).

**Comment by armab** [comment]
@enykeev I see what you meant about staging and unstable:
https://stackstorm.slack.com/archives/packages/p1455133096005090

So for enterprise only prod + staging is needed for now. I thought you talked about community repos.

**Comment by armab** [comment]
@enykeev I adjusted and included your `packagecloud.sh` script, so we now deploy to PackageCloud.io as well.

Please take a look at first message for updated `TODO`/list of problems: https://github.com/StackStorm/st2-packages/issues/130#issue-129888172

From this point I think you can play in `st2web` and `st2flow` with it. Should be OK enough to use.

**Comment by armab** [comment]
This is finished, we're on PackageCloud.

The only task which we didn't tried remains:
* [ ] Research/Try `yum`/`apt` [repo mirroring](https://packagecloud.io/StackStorm/staging-unstable/mirror)

Opened https://github.com/StackStorm/st2-packages/issues/207 instead
