### ISSUE TITLE
Deprecate Debian Wheezy and Jessie

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#365]
Closes https://github.com/StackStorm/st2/issues/2799

We actually build packages for [`debian wheezy` and `debian jessie`](https://github.com/StackStorm/st2-packages/blob/master/circle.yml#L20). That locks `2` CircleCI containers, increases overall build time and queue.

> FYI: `Debian Wheezy` [was needed](https://github.com/StackStorm/st2-dockerfiles/issues/23
) because of its small size as base for Docker images.

These packages never reached the `stable` repos from `staging`. Maybe just 1 or 2 persons asked if we support it.

Some `deb` code is in place for them and must be cleaned up as well.

Looks like it's finally safe to remove them or there is a chance we'll need pure Debian support?

### TODO
- [x] `st2-packages` https://github.com/StackStorm/st2-packages/pull/471
  - [x] `deb` packaging changes/cleanup
- [x] `mistral` https://github.com/StackStorm/mistral/pull/30
- [x] `st2chatops` https://github.com/StackStorm/st2chatops/pull/79
- [x] `st2web` https://github.com/StackStorm/st2web/pull/382
- [x] `bwc` https://github.com/StackStorm/bwc-enterprise-packages/pull/17
- [x] `bwc-ui` https://github.com/StackStorm/bwc-ui/pull/13
- [x] `st2-auth-ldap` https://github.com/StackStorm/st2-enterprise-auth-backend-ldap/pull/34
- [x] `st2flow` https://github.com/StackStorm/st2flow/pull/121
- [x] `st2ci` https://github.com/StackStorm/st2ci/pull/101
- [x] `st2-dockerfiles` https://github.com/StackStorm/st2-dockerfiles/pull/54
  - [x] Remove Dockerfiles
  - [ ] Delete Docker Hub Images
  - [ ] Delete quay.io Images
---
- [ ] https://github.com/StackStorm/bwc-topology/pull/165
- [ ] https://github.com/StackStorm/bwc-cli/pull/64
- [ ] https://github.com/StackStorm/sandbox-actions/pull/288
- [ ] https://github.com/StackStorm/bwc-ipfabric-packs/pull/64
- [ ] https://github.com/StackStorm/ixp_essentials/pull/22
- [ ] https://github.com/StackStorm/network_essentials/pull/129
- [ ] https://github.com/StackStorm/bwc-ipfabric-suite-packages/pull/6
- [ ] https://github.com/StackStorm/dcfabric-suite-packages/pull/30

**Comment by LindsayHill** [comment]
Don't think we'll ever offer pure Debian support. People are welcome to build packages & run it on Debian, but main focus will be Ubuntu + RHEL/CentOS

**Comment by armab** [comment]
Done.
We're not building `wheezy` & `jessie` packages during our release process now.
