### ISSUE TITLE
st2 fails to run immediately after service restart

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#429]
> Experienced during the https://github.com/StackStorm/ops-infra/pull/107 work

We noticed this issue several times before.

If st2 is restarted and we run command immediately after startup, - it fails probably because init reports status too fast or something like that.

This needs investigation and proper fix.

### Steps to reproduce
```sh
sudo st2ctl restart && st2 action list
```

### Error
```
# st2ctl restart && st2 action list
Failed to stop st2chatops.service: Unit st2chatops.service not loaded.
Failed to stop mistral.service: Unit mistral.service not loaded.
Failed to start st2chatops.service: Unit st2chatops.service not found.
Failed to start mistral.service: Unit mistral.service not found.
##### st2 components status #####
st2actionrunner PID: 25339
st2actionrunner PID: 25341
st2actionrunner PID: 25346
st2actionrunner PID: 25349
st2actionrunner PID: 25352
st2actionrunner PID: 25355
st2actionrunner PID: 25359
st2actionrunner PID: 25363
st2actionrunner PID: 25366
st2actionrunner PID: 25369
st2api PID: 25374
st2stream PID: 25377
st2auth PID: 25383
st2garbagecollector PID: 25387
st2notifier PID: 25391
st2resultstracker PID: 25395
st2rulesengine PID: 25399
st2sensorcontainer PID: 25403
st2chatops is not running.
mistral-server is not running.
mistral-api is not running.

ERROR: HTTPConnectionPool(host='127.0.0.1', port=9101): Max retries exceeded with url: /v1/actions (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f1d2dddd250>: Failed to establish a new connection: [Errno 111] Connection refused',))

```

after a couple of seconds, running `st2 action list` works OK.

### TODO
- [x] Check if `CentOS7` with systemd is affected
- [x] Check if `Ubuntu Trusty` with upstart is affected
- [x] Check if `CentOS6` with SysvInit is affected
- [x] Investigate the Fix https://github.com/StackStorm/st2-packages/pull/435#issuecomment-284006738
- [x] Remove hack in [`curl | bash`](https://github.com/StackStorm/st2-packages/blob/788761323d3402c29efa87c2678de684a77eb6f6/scripts/st2bootstrap-deb.sh#L554-L557)
- [x] Remove hack in [`ansible-st2`](https://github.com/StackStorm/ansible-st2/blob/66f65afd663964626474402143028279d40ab180/roles/st2smoketests/tasks/main.yml#L28-L32) https://github.com/StackStorm/ansible-st2/pull/128
- [x] Remove hack in `st2-packages` tests (sleep 15s after services start)
- [x] Add `st2ctl restart && st2 action list` smoke test
- [x] Fix
  - [x] EL6 (sysvinit)
  - [x] EL7 (systemd)
  - [x] Trusty (upstart)
  - [x] Xenial (systemd)
- [x] Final Testing (incl. `curl|bash`)
  - [x] EL6?
  - [x] EL7
  - [x] Trusty
  - [x] Xenial
- [x] In addition to fixing the root cause: research timeouts + retries in `st2client` (pretty obvious strategy used in any package manager won't hurt) https://github.com/StackStorm/st2/issues/3257

I'll dig into this roadblock, otherwise entire user story under `xenial` is wasted.

**Comment by armab** [comment]
Apart of `Xenial`, could catch *almost* the same problem on `CentOS7`:

```sh
sudo service st2api restart && st2 action list

Redirecting to /bin/systemctl restart  st2api.service
ERROR: HTTPConnectionPool(host='127.0.0.1', port=9101): Max retries exceeded with url: /v1/actions (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x27442d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

Most probably `st2api` with gunicorn something.

**Comment by armab** [comment]
Oh noes, same for `Trusty` (upstart):

```
vagrant@ubuntu14:~$ sudo service st2api restart && st2 action list

st2api stop/waiting
st2api start/running, process 2837
ERROR: HTTPConnectionPool(host='127.0.0.1', port=9101): Max retries exceeded with url: /v1/actions (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fa6ddbeb9d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by armab** [comment]
Fixed via https://github.com/StackStorm/st2-packages/issues/435

**Comment by armab** [comment]
Another bug related to this (but with register content failure) discovered for Xenial: https://github.com/StackStorm/st2-packages/issues/445

**Comment by armab** [comment]
Another bug related to this (but with execution run failure on fresh RabbitMQ) discovered for Xenial: https://github.com/StackStorm/st2/issues/3290
